/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErrorRouteImport } from './routes/error'

const TestLazyRouteImport = createFileRoute('/test')()
const LoginLazyRouteImport = createFileRoute('/login')()
const HistoryLazyRouteImport = createFileRoute('/history')()
const DashboardLazyRouteImport = createFileRoute('/dashboard')()
const IndexLazyRouteImport = createFileRoute('/')()
const TripIndexLazyRouteImport = createFileRoute('/trip/')()
const ReimbursementIndexLazyRouteImport = createFileRoute('/reimbursement/')()
const TripFinanceHistoryLazyRouteImport = createFileRoute(
  '/trip/finance-history',
)()
const TripFinanceLazyRouteImport = createFileRoute('/trip/finance')()
const TripCreateLazyRouteImport = createFileRoute('/trip/create')()
const ReimbursementUpdateLazyRouteImport = createFileRoute(
  '/reimbursement/update',
)()
const ReimbursementManagerHistoryLazyRouteImport = createFileRoute(
  '/reimbursement/manager-history',
)()
const ReimbursementFinanceHistoryLazyRouteImport = createFileRoute(
  '/reimbursement/finance-history',
)()
const ApprovalManagerLazyRouteImport = createFileRoute('/approval/manager')()
const ApprovalFinanceLazyRouteImport = createFileRoute('/approval/finance')()

const TestLazyRoute = TestLazyRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/test.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const HistoryLazyRoute = HistoryLazyRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/history.lazy').then((d) => d.Route))
const DashboardLazyRoute = DashboardLazyRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/dashboard.lazy').then((d) => d.Route))
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/error.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const TripIndexLazyRoute = TripIndexLazyRouteImport.update({
  id: '/trip/',
  path: '/trip/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trip/index.lazy').then((d) => d.Route))
const ReimbursementIndexLazyRoute = ReimbursementIndexLazyRouteImport.update({
  id: '/reimbursement/',
  path: '/reimbursement/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reimbursement/index.lazy').then((d) => d.Route),
)
const TripFinanceHistoryLazyRoute = TripFinanceHistoryLazyRouteImport.update({
  id: '/trip/finance-history',
  path: '/trip/finance-history',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/trip/finance-history.lazy').then((d) => d.Route),
)
const TripFinanceLazyRoute = TripFinanceLazyRouteImport.update({
  id: '/trip/finance',
  path: '/trip/finance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trip/finance.lazy').then((d) => d.Route))
const TripCreateLazyRoute = TripCreateLazyRouteImport.update({
  id: '/trip/create',
  path: '/trip/create',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/trip/create.lazy').then((d) => d.Route))
const ReimbursementUpdateLazyRoute = ReimbursementUpdateLazyRouteImport.update({
  id: '/reimbursement/update',
  path: '/reimbursement/update',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reimbursement/update.lazy').then((d) => d.Route),
)
const ReimbursementManagerHistoryLazyRoute =
  ReimbursementManagerHistoryLazyRouteImport.update({
    id: '/reimbursement/manager-history',
    path: '/reimbursement/manager-history',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/reimbursement/manager-history.lazy').then((d) => d.Route),
  )
const ReimbursementFinanceHistoryLazyRoute =
  ReimbursementFinanceHistoryLazyRouteImport.update({
    id: '/reimbursement/finance-history',
    path: '/reimbursement/finance-history',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/reimbursement/finance-history.lazy').then((d) => d.Route),
  )
const ApprovalManagerLazyRoute = ApprovalManagerLazyRouteImport.update({
  id: '/approval/manager',
  path: '/approval/manager',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/approval/manager.lazy').then((d) => d.Route),
)
const ApprovalFinanceLazyRoute = ApprovalFinanceLazyRouteImport.update({
  id: '/approval/finance',
  path: '/approval/finance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/approval/finance.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/error': typeof ErrorRoute
  '/dashboard': typeof DashboardLazyRoute
  '/history': typeof HistoryLazyRoute
  '/login': typeof LoginLazyRoute
  '/test': typeof TestLazyRoute
  '/approval/finance': typeof ApprovalFinanceLazyRoute
  '/approval/manager': typeof ApprovalManagerLazyRoute
  '/reimbursement/finance-history': typeof ReimbursementFinanceHistoryLazyRoute
  '/reimbursement/manager-history': typeof ReimbursementManagerHistoryLazyRoute
  '/reimbursement/update': typeof ReimbursementUpdateLazyRoute
  '/trip/create': typeof TripCreateLazyRoute
  '/trip/finance': typeof TripFinanceLazyRoute
  '/trip/finance-history': typeof TripFinanceHistoryLazyRoute
  '/reimbursement': typeof ReimbursementIndexLazyRoute
  '/trip': typeof TripIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/error': typeof ErrorRoute
  '/dashboard': typeof DashboardLazyRoute
  '/history': typeof HistoryLazyRoute
  '/login': typeof LoginLazyRoute
  '/test': typeof TestLazyRoute
  '/approval/finance': typeof ApprovalFinanceLazyRoute
  '/approval/manager': typeof ApprovalManagerLazyRoute
  '/reimbursement/finance-history': typeof ReimbursementFinanceHistoryLazyRoute
  '/reimbursement/manager-history': typeof ReimbursementManagerHistoryLazyRoute
  '/reimbursement/update': typeof ReimbursementUpdateLazyRoute
  '/trip/create': typeof TripCreateLazyRoute
  '/trip/finance': typeof TripFinanceLazyRoute
  '/trip/finance-history': typeof TripFinanceHistoryLazyRoute
  '/reimbursement': typeof ReimbursementIndexLazyRoute
  '/trip': typeof TripIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/error': typeof ErrorRoute
  '/dashboard': typeof DashboardLazyRoute
  '/history': typeof HistoryLazyRoute
  '/login': typeof LoginLazyRoute
  '/test': typeof TestLazyRoute
  '/approval/finance': typeof ApprovalFinanceLazyRoute
  '/approval/manager': typeof ApprovalManagerLazyRoute
  '/reimbursement/finance-history': typeof ReimbursementFinanceHistoryLazyRoute
  '/reimbursement/manager-history': typeof ReimbursementManagerHistoryLazyRoute
  '/reimbursement/update': typeof ReimbursementUpdateLazyRoute
  '/trip/create': typeof TripCreateLazyRoute
  '/trip/finance': typeof TripFinanceLazyRoute
  '/trip/finance-history': typeof TripFinanceHistoryLazyRoute
  '/reimbursement/': typeof ReimbursementIndexLazyRoute
  '/trip/': typeof TripIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/test'
    | '/approval/finance'
    | '/approval/manager'
    | '/reimbursement/finance-history'
    | '/reimbursement/manager-history'
    | '/reimbursement/update'
    | '/trip/create'
    | '/trip/finance'
    | '/trip/finance-history'
    | '/reimbursement'
    | '/trip'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/test'
    | '/approval/finance'
    | '/approval/manager'
    | '/reimbursement/finance-history'
    | '/reimbursement/manager-history'
    | '/reimbursement/update'
    | '/trip/create'
    | '/trip/finance'
    | '/trip/finance-history'
    | '/reimbursement'
    | '/trip'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/dashboard'
    | '/history'
    | '/login'
    | '/test'
    | '/approval/finance'
    | '/approval/manager'
    | '/reimbursement/finance-history'
    | '/reimbursement/manager-history'
    | '/reimbursement/update'
    | '/trip/create'
    | '/trip/finance'
    | '/trip/finance-history'
    | '/reimbursement/'
    | '/trip/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ErrorRoute: typeof ErrorRoute
  DashboardLazyRoute: typeof DashboardLazyRoute
  HistoryLazyRoute: typeof HistoryLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  TestLazyRoute: typeof TestLazyRoute
  ApprovalFinanceLazyRoute: typeof ApprovalFinanceLazyRoute
  ApprovalManagerLazyRoute: typeof ApprovalManagerLazyRoute
  ReimbursementFinanceHistoryLazyRoute: typeof ReimbursementFinanceHistoryLazyRoute
  ReimbursementManagerHistoryLazyRoute: typeof ReimbursementManagerHistoryLazyRoute
  ReimbursementUpdateLazyRoute: typeof ReimbursementUpdateLazyRoute
  TripCreateLazyRoute: typeof TripCreateLazyRoute
  TripFinanceLazyRoute: typeof TripFinanceLazyRoute
  TripFinanceHistoryLazyRoute: typeof TripFinanceHistoryLazyRoute
  ReimbursementIndexLazyRoute: typeof ReimbursementIndexLazyRoute
  TripIndexLazyRoute: typeof TripIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/': {
      id: '/trip/'
      path: '/trip'
      fullPath: '/trip'
      preLoaderRoute: typeof TripIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursement/': {
      id: '/reimbursement/'
      path: '/reimbursement'
      fullPath: '/reimbursement'
      preLoaderRoute: typeof ReimbursementIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/finance-history': {
      id: '/trip/finance-history'
      path: '/trip/finance-history'
      fullPath: '/trip/finance-history'
      preLoaderRoute: typeof TripFinanceHistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/finance': {
      id: '/trip/finance'
      path: '/trip/finance'
      fullPath: '/trip/finance'
      preLoaderRoute: typeof TripFinanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trip/create': {
      id: '/trip/create'
      path: '/trip/create'
      fullPath: '/trip/create'
      preLoaderRoute: typeof TripCreateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursement/update': {
      id: '/reimbursement/update'
      path: '/reimbursement/update'
      fullPath: '/reimbursement/update'
      preLoaderRoute: typeof ReimbursementUpdateLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursement/manager-history': {
      id: '/reimbursement/manager-history'
      path: '/reimbursement/manager-history'
      fullPath: '/reimbursement/manager-history'
      preLoaderRoute: typeof ReimbursementManagerHistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reimbursement/finance-history': {
      id: '/reimbursement/finance-history'
      path: '/reimbursement/finance-history'
      fullPath: '/reimbursement/finance-history'
      preLoaderRoute: typeof ReimbursementFinanceHistoryLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/manager': {
      id: '/approval/manager'
      path: '/approval/manager'
      fullPath: '/approval/manager'
      preLoaderRoute: typeof ApprovalManagerLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval/finance': {
      id: '/approval/finance'
      path: '/approval/finance'
      fullPath: '/approval/finance'
      preLoaderRoute: typeof ApprovalFinanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ErrorRoute: ErrorRoute,
  DashboardLazyRoute: DashboardLazyRoute,
  HistoryLazyRoute: HistoryLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  TestLazyRoute: TestLazyRoute,
  ApprovalFinanceLazyRoute: ApprovalFinanceLazyRoute,
  ApprovalManagerLazyRoute: ApprovalManagerLazyRoute,
  ReimbursementFinanceHistoryLazyRoute: ReimbursementFinanceHistoryLazyRoute,
  ReimbursementManagerHistoryLazyRoute: ReimbursementManagerHistoryLazyRoute,
  ReimbursementUpdateLazyRoute: ReimbursementUpdateLazyRoute,
  TripCreateLazyRoute: TripCreateLazyRoute,
  TripFinanceLazyRoute: TripFinanceLazyRoute,
  TripFinanceHistoryLazyRoute: TripFinanceHistoryLazyRoute,
  ReimbursementIndexLazyRoute: ReimbursementIndexLazyRoute,
  TripIndexLazyRoute: TripIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
